// <auto-generated />
using Amortization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amortization.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240201195553_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amortization.Data.MortgageParameter", b =>
                {
                    b.Property<int>("MortgageParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MortgageParameterId"));

                    b.Property<double>("AnnualInterestRate")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfPayments")
                        .HasColumnType("int");

                    b.Property<double>("PrincipalLoanAmount")
                        .HasColumnType("float");

                    b.HasKey("MortgageParameterId");

                    b.ToTable("MortgageParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
